### ISSUE TITLE
No dcmqi binaries are available for the `latest` tag

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#260]
JC, why is it so fragile?

Would it be possible to change the scripts so that the error is somehow reported via CI?

![image](https://user-images.githubusercontent.com/313942/27237302-9c709ad6-5296-11e7-9a18-5ca3a2345efe.png)

**Comment by fedorov** [comment]
No errors for CIs:

![image](https://user-images.githubusercontent.com/313942/27237354-c8fff8f8-5296-11e7-9ac4-df3729535523.png)

**Comment by jcfr** [comment]
Here are the summary from the different CI. 

Look like the `COMMIT_DATE` used by the upload script is `20170615` whereas the one associated with the package is `20170614`.

I will have an other look later tonight

See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#mini-language-for-packages-selection

It look like this code is returning `20170614`. See https://github.com/QIICR/dcmqi/blob/99bbbbb1e5427b999f38c9df9f39a6717bd05a6a/CMake/dcmqiVersion.cmake#L123-L125

```
           --prerelease-packages "c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64-*.zip" `
           --prerelease-packages-clear-pattern "dcmqi-*-win64-*" `
           --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
```

```
Updating prerelease package keep pattern [*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
   <COMMIT_DATE> -> 20170615
   <COMMIT_SHORT_SHA> -> 99bbbbb
 Checking if HEAD is a release tag
 Checking if HEAD is a release tag - no (creating prerelease)
 
 release latest: already exists
 
 uploading 'latest' release asset(s) (found 1):
   uploading c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-1.0.5-win64-20170614-99bbbbb.zip
   download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-win64-20170614-99bbbbb.zip
 
 deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 0, not-matched: 2):
   deleting dcmqi-1.0.5-win64-20170613-728b4a3.zip
   deleting dcmqi-1.0.5-win64-20170614-99bbbbb.zip
```

### Linux (circle)

```
ci_addons publish_github_release qiicr/dcmqi \
   --prerelease-packages "build/dcmqi-build/dcmqi-*-linux-*.tar.gz" \
   --prerelease-packages-clear-pattern "dcmqi-*-linux-*" \
   --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
Updating prerelease package keep pattern [*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
  <COMMIT_DATE> -> 20170615
  <COMMIT_SHORT_SHA> -> 99bbbbb
Checking if HEAD is a release tag
Checking if HEAD is a release tag - no (creating prerelease)

release latest: already exists

uploading 'latest' release asset(s) (found 2):
  uploading build/dcmqi-build/dcmqi-1.0.5-linux-20170613-728b4a3.tar.gz
  skipping (asset with same name already exists)
  download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-linux-20170613-728b4a3.tar.gz

  uploading build/dcmqi-build/dcmqi-1.0.5-linux-20170614-99bbbbb.tar.gz
  download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-linux-20170614-99bbbbb.tar.gz

deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 0, not-matched: 1):
  deleting dcmqi-1.0.5-linux-20170613-728b4a3.tar.gz
  deleting dcmqi-1.0.5-linux-20170614-99bbbbb.tar.gz

resolved 'master' to '99bbbbb1e5427b999f38c9df9f39a6717bd05a6a'
updating 'latest' release: 
  name: 'Latest (updated on 2017-06-15 02:06 UTC)' -> 'Latest (updated on 2017-06-15 03:06 UTC)'

```

### MacOSX (travis)

```
Updating prerelease package keep pattern [*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
  <COMMIT_DATE> -> 20170615
  <COMMIT_SHORT_SHA> -> 99bbbbb

Checking if HEAD is a release tag
Checking if HEAD is a release tag - no (creating prerelease)
release latest: already exists

uploading 'latest' release asset(s) (found 1):
  uploading /Users/travis/build/QIICR/dcmqi-build/dcmqi-build/dcmqi-1.0.5-mac-20170614-99bbbbb.tar.gz
  download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-mac-20170614-99bbbbb.tar.gz

deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 0, not-matched: 0):
  deleting dcmqi-1.0.5-mac-20170613-728b4a3.tar.gz
  deleting dcmqi-1.0.5-mac-20170614-99bbbbb.tar.gz

resolved 'master' to '99bbbbb1e5427b999f38c9df9f39a6717bd05a6a'
```

### Windows (Appveyor)

```
02:43] ci_addons publish_github_release qiicr/dcmqi `
[00:02:43]    --exit-success-if-missing-token `
[00:02:43]    --release-packages "c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64.zip" `
[00:02:43]    --prerelease-packages "c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64-*.zip" `
[00:02:43]    --prerelease-packages-clear-pattern "dcmqi-*-win64-*" `
[00:02:43]    --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
[00:02:43] 
[00:03:11] 
[00:03:11] Cancelling 'queued' AppVeyor build(s) associated with tag matching [^latest(-tmp)?$]
[00:03:13] done
[00:03:13] Updating prerelease package keep pattern [*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
[00:03:13]   <COMMIT_DATE> -> 20170615
[00:03:13]   <COMMIT_SHORT_SHA> -> 99bbbbb
[00:03:13] Checking if HEAD is a release tag
[00:03:13] Checking if HEAD is a release tag - no (creating prerelease)
[00:03:13] 
[00:03:13] release latest: already exists
[00:03:13] 
[00:03:13] uploading 'latest' release asset(s) (found 1):
[00:03:13]   uploading c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-1.0.5-win64-20170614-99bbbbb.zip
[00:03:13]   download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-win64-20170614-99bbbbb.zip
[00:03:13] 
[00:03:13] deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 0, not-matched: 2):
[00:03:13]   deleting dcmqi-1.0.5-win64-20170613-728b4a3.zip
[00:03:13]   deleting dcmqi-1.0.5-win64-20170614-99bbbbb.zip
[00:03:13] 
[00:03:13] resolved 'master' to '99bbbbb1e5427b999f38c9df9f39a6717bd05a6a'
[00:03:13] updating 'latest' release: 
[00:03:13]   target_commitish: '728b4a38653f0a556bd4e2356c41d689da2c2c18' -> '99bbbbb1e5427b999f38c9df9f39a6717bd05a6a'
[00:03:13]   tag_name: 'latest' -> 'latest-tmp'
[00:03:13] 
[00:03:13] deleting reference refs/tags/latest
[00:03:13] updating 'latest-tmp' release: 
[00:03:13]   tag_name: 'latest-tmp' -> 'latest'
[00:03:13] 
[00:03:13] deleting reference refs/tags/latest-tmp
[00:03:13] updating 'latest' release: 
[00:03:13]   target_commitish: '728b4a38653f0a556bd4e2356c41d689da2c2c18' -> '99bbbbb1e5427b999f38c9df9f39a6717bd05a6a'
[00:03:13] 
[00:03:13] updating 'latest' release: 
[00:03:13]   name: 'Latest (updated on 2017-06-13 23:06 UTC)' -> 'Latest (updated on 2017-06-15 02:06 UTC)'
```

**Comment by jcfr** [comment]
DCMQI package date is obtained here: https://github.com/QIICR/dcmqi/blob/99bbbbb1e5427b999f38c9df9f39a6717bd05a6a/CMake/FindGit.cmake#L116-L121

using 

```
${GIT_EXECUTABLE} show -s --format="%ci" ${${prefix}_WC_REVISION_HASH}
```

and the one associated with the upload script is obtained using: 

```
git show -s --format="%cd" --date=local
```

**Comment by jcfr** [comment]
* ci: committer date, ISO 8601-like format
* cd: committer date (format respects --date= option)


I will fix the upload script later and address this.

**Comment by fedorov** [comment]
Thanks a lot for looking into this JC, I hope this is something that is not very difficult to address.

**Comment by fedorov** [comment]
@jcfr when I try to run package upload manually on mac, I get this error:

```
Traceback (most recent call last):
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/scikit_ci_addons-0.16.0-py2.7.egg/anyci/publish_github_release.py", line 439, in <module>
    main()
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/scikit_ci_addons-0.16.0-py2.7.egg/anyci/publish_github_release.py", line 432, in main
    _upload_prerelease(args)
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/scikit_ci_addons-0.16.0-py2.7.egg/anyci/publish_github_release.py", line 318, in _upload_prerelease
    args.dry_run
  File "build/bdist.macosx-10.10-x86_64/egg/github_release.py", line 116, in with_check_for_credentials
  File "build/bdist.macosx-10.10-x86_64/egg/github_release.py", line 739, in gh_asset_upload
  File "build/bdist.macosx-10.10-x86_64/egg/github_release.py", line 683, in _upload_release_file
  File "build/bdist.macosx-10.10-x86_64/egg/github_release.py", line 65, in _request
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/requests-2.18.1-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/requests-2.18.1-py2.7.egg/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/requests-2.18.1-py2.7.egg/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/fedorov/.pyenv/versions/2.7.8/lib/python2.7/site-packages/requests-2.18.1-py2.7.egg/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'uploads.github.com' doesn't match either of '*.githubusercontent.com', 'githubusercontent.com'
```

**Comment by fedorov** [comment]
Looks like the issue in https://github.com/j0057/github-release/issues/1

**Comment by jcfr** [comment]
Now attending the Slicer project week, I will have some time to address this.

**Comment by fedorov** [comment]
@jcfr any updates on this bug?

**Comment by fedorov** [comment]
After latest commit, packages show up, but dated April, and for Linux the hash corresponds to an earlier commit. I understand CI failed for the latest commit on Linux, but I would expect the result should be missing package for Linux, the current behavior is somewhat strange.

**Comment by fedorov** [comment]
As of ed85c8a21433e4b6600b5c6d2553cf2dcf6e4067, nightly binaries were again not generated.

**Comment by jcfr** [comment]
Back in the office, i will work on this.

**Comment by fedorov** [comment]
Thank you @jcfr.

With the latest commit, all binaries are present, but from different commits ... 

![image](https://user-images.githubusercontent.com/313942/28035915-4c4c5f30-6584-11e7-9bf7-d8d485f38d98.png)

**Comment by fedorov** [comment]
@jcfr when will you have time to look into this really critical issue?

At this point it breaks our CI, at least on appveyor:

```
[00:02:19] ci_addons publish_github_release qiicr/dcmqi `
[00:02:19]    --exit-success-if-missing-token `
[00:02:19]    --release-packages "c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64.zip" `
[00:02:19]    --prerelease-packages "c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64-*.zip" `
[00:02:19]    --prerelease-packages-clear-pattern "dcmqi-*-win64-*" `
[00:02:19]    --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
[00:02:19] 
[00:02:43] Updating prerelease package keep pattern [*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
[00:02:43]   <COMMIT_DATE> -> 20170720
[00:02:43]   <COMMIT_SHORT_SHA> -> ca94642
[00:02:43] Checking if HEAD is a release tag
[00:02:43] Checking if HEAD is a release tag - no (creating prerelease)
[00:02:43] 
[00:02:43] release latest: already exists
[00:02:43] 
[00:02:43] uploading 'latest' release asset(s) (found 1):
[00:02:43]   uploading c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-1.0.5-win64-20170720-ca94642.zip
[00:02:43]   download_url: https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-win64-20170720-ca94642.zip
[00:02:43] 
[00:02:43] deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 1, not-matched: 2):
[00:02:43]   deleting dcmqi-1.0.5-win64-20170720-c30a2a3.zip
[00:02:43] 
[00:02:43] resolved 'master' to 'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43] updating 'latest-tmp' release: 
[00:02:43]   target_commitish: 'c30a2a37b6c0dfada25dd52844182913168e2c54' -> 'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43]   tag_name: 'latest-tmp' -> 'latest-tmp-tmp'
[00:02:43] 
[00:02:43] deleting reference refs/tags/latest-tmp
[00:02:43] updating 'latest-tmp-tmp' release: 
[00:02:43]   tag_name: 'latest-tmp-tmp' -> 'latest-tmp'
[00:02:43] 
[00:02:43] deleting reference refs/tags/latest-tmp-tmp
[00:02:43] updating 'latest' release: 
[00:02:43]   target_commitish: '6d01d51029eae4c771fd02a7129aa5b940c01a95' -> 'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43]   tag_name: 'latest' -> 'latest-tmp'
[00:02:43] 
[00:02:43] ci_addons : Traceback (most recent call last):
[00:02:43] At line:1 char:1
[00:02:43] + ci_addons publish_github_release qiicr/dcmqi `
[00:02:43] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:02:43]     + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
[00:02:43]     + FullyQualifiedErrorId : NativeCommandError
[00:02:43]  
[00:02:43]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 439, in <module>
[00:02:43]     main()
[00:02:43]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 432, in main
[00:02:43]     _upload_prerelease(args)
[00:02:43]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 342, in _upload_prerelease
[00:02:43]     target_commitish=sha
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 116, in with_check_for_credentials
[00:02:43]     return func(*args, **kwargs)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 479, in gh_release_edit
[00:02:43]     patch_release(repo_name, current_tag_name, **attributes)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 327, in patch_release
[00:02:43]     dry_run
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 301, in _update_release_sha
[00:02:43]     dry_run=dry_run)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 357, in patch_release
[00:02:43]     response.raise_for_status()
[00:02:43]   File "c:\python27-x64\lib\site-packages\requests\models.py", line 937, in raise_for_status
[00:02:43]     raise HTTPError(http_error_msg, response=self)
[00:02:43] requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:02:43] 
[00:02:43] Command executed with exception:   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 439, in <module>
[00:02:43]     main()
[00:02:43]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 432, in main
[00:02:43]     _upload_prerelease(args)
[00:02:43]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 342, in _upload_prerelease
[00:02:43]     target_commitish=sha
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 116, in with_check_for_credentials
[00:02:43]     return func(*args, **kwargs)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 479, in gh_release_edit
[00:02:43]     patch_release(repo_name, current_tag_name, **attributes)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 327, in patch_release
[00:02:43]     dry_run
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 301, in _update_release_sha
[00:02:43]     dry_run=dry_run)
[00:02:43]   File "c:\python27-x64\lib\site-packages\github_release.py", line 357, in patch_release
[00:02:43]     response.raise_for_status()
[00:02:43]   File "c:\python27-x64\lib\site-packages\requests\models.py", line 937, in raise_for_status
[00:02:43]     raise HTTPError(http_error_msg, response=self)
[00:02:43] requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:02:43] 
```

**Comment by jcfr** [comment]
Hi,

I am planning to test my changes in the next few days. Will all the travel
it has been challenging to seat and finalize.

Jc

On Jul 20, 2017 4:33 PM, "Andrey Fedorov" <notifications@github.com> wrote:

@jcfr <https://github.com/jcfr> when will you have time to look into this
really critical issue?

At this point it breaks our CI, at least on appveyor:

[00:02:19] ci_addons publish_github_release qiicr/dcmqi `
[00:02:19]    --exit-success-if-missing-token `
[00:02:19]    --release-packages
"c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64.zip" `
[00:02:19]    --prerelease-packages
"c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-*-win64-*.zip" `
[00:02:19]    --prerelease-packages-clear-pattern "dcmqi-*-win64-*" `
[00:02:19]    --prerelease-packages-keep-pattern
"*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
[00:02:19]
[00:02:43] Updating prerelease package keep pattern
[*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*]
[00:02:43]   <COMMIT_DATE> -> 20170720
[00:02:43]   <COMMIT_SHORT_SHA> -> ca94642
[00:02:43] Checking if HEAD is a release tag
[00:02:43] Checking if HEAD is a release tag - no (creating prerelease)
[00:02:43]
[00:02:43] release latest: already exists
[00:02:43]
[00:02:43] uploading 'latest' release asset(s) (found 1):
[00:02:43]   uploading
c:\dcmqi\dcmqi-build\dcmqi-build\dcmqi-1.0.5-win64-20170720-ca94642.zip
[00:02:43]   download_url:
https://github.com/QIICR/dcmqi/releases/download/latest/dcmqi-1.0.5-win64-20170720-ca94642.zip
[00:02:43]
[00:02:43] deleting 'latest' release asset(s) (matched: 2,
matched-but-keep: 1, not-matched: 2):
[00:02:43]   deleting dcmqi-1.0.5-win64-20170720-c30a2a3.zip
[00:02:43]
[00:02:43] resolved 'master' to 'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43] updating 'latest-tmp' release:
[00:02:43]   target_commitish:
'c30a2a37b6c0dfada25dd52844182913168e2c54' ->
'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43]   tag_name: 'latest-tmp' -> 'latest-tmp-tmp'
[00:02:43]
[00:02:43] deleting reference refs/tags/latest-tmp
[00:02:43] updating 'latest-tmp-tmp' release:
[00:02:43]   tag_name: 'latest-tmp-tmp' -> 'latest-tmp'
[00:02:43]
[00:02:43] deleting reference refs/tags/latest-tmp-tmp
[00:02:43] updating 'latest' release:
[00:02:43]   target_commitish:
'6d01d51029eae4c771fd02a7129aa5b940c01a95' ->
'ca94642ccf35403594c82eafe1ae069ee3161450'
[00:02:43]   tag_name: 'latest' -> 'latest-tmp'
[00:02:43]
[00:02:43] ci_addons : Traceback (most recent call last):
[00:02:43] At line:1 char:1
[00:02:43] + ci_addons publish_github_release qiicr/dcmqi `
[00:02:43] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:02:43]     + CategoryInfo          : NotSpecified: (Traceback
(most recent call last)::String) [], RemoteException
[00:02:43]     + FullyQualifiedErrorId : NativeCommandError
[00:02:43]
[00:02:43]   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 439, in <module>
[00:02:43]     main()
[00:02:43]   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 432, in main
[00:02:43]     _upload_prerelease(args)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 342, in _upload_prerelease
[00:02:43]     target_commitish=sha
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 116, in
with_check_for_credentials
[00:02:43]     return func(*args, **kwargs)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 479, in
gh_release_edit
[00:02:43]     patch_release(repo_name, current_tag_name, **attributes)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 327, in
patch_release
[00:02:43]     dry_run
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 301, in
_update_release_sha
[00:02:43]     dry_run=dry_run)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 357, in
patch_release
[00:02:43]     response.raise_for_status()
[00:02:43]   File
"c:\python27-x64\lib\site-packages\requests\models.py", line 937, in
raise_for_status
[00:02:43]     raise HTTPError(http_error_msg, response=self)
[00:02:43] requests.exceptions.HTTPError: 422 Client Error:
Unprocessable Entity for url:
https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:02:43]
[00:02:43] Command executed with exception:   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 439, in <module>
[00:02:43]     main()
[00:02:43]   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 432, in main
[00:02:43]     _upload_prerelease(args)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\anyci\publish_github_release.py",
line 342, in _upload_prerelease
[00:02:43]     target_commitish=sha
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 116, in
with_check_for_credentials
[00:02:43]     return func(*args, **kwargs)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 479, in
gh_release_edit
[00:02:43]     patch_release(repo_name, current_tag_name, **attributes)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 327, in
patch_release
[00:02:43]     dry_run
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 301, in
_update_release_sha
[00:02:43]     dry_run=dry_run)
[00:02:43]   File
"c:\python27-x64\lib\site-packages\github_release.py", line 357, in
patch_release
[00:02:43]     response.raise_for_status()
[00:02:43]   File
"c:\python27-x64\lib\site-packages\requests\models.py", line 937, in
raise_for_status
[00:02:43]     raise HTTPError(http_error_msg, response=self)
[00:02:43] requests.exceptions.HTTPError: 422 Client Error:
Unprocessable Entity for url:
https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:02:43]

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/QIICR/dcmqi/issues/260#issuecomment-316821747>, or mute
the thread

**Comment by fedorov** [comment]
@jcfr should we keep the issue open until it is confirmed the problem is resolved?

**Comment by jcfr** [comment]
Yes. I still need to update the version of scikit-ci-addons pulled in dcmqi, that will allow us to test.

**Comment by jcfr** [comment]
As soon as tests for #284 return green, I will merge later tonight and we should be able to confirm if it fixes the problem. 

PR need to be merged late enough in the day to confirm that timezone different is not affecting the nightly release upload.

**Comment by jcfr** [comment]
To  be in the same condition as the glitch leading to this issue, PR #284 should be merged after 10pm.

**Comment by fedorov** [comment]
@jcfr can you explain what's going on?

* all CIs failed
* but packages for all platforms are available for the latest commit
* and they are dated 13 days ago, and the commit message is from a commit 13 days ago, although the commit hash they are tagged with was from yesterday...

Should we try to go back to the out-of-the-box CI package deployment as we did initially and do for DCMTK here: https://github.com/QIICR/dcmtk-dcmqi/blob/dcmqi/appveyor.yml#L32-L38?

![image](https://user-images.githubusercontent.com/313942/28678144-97b952d4-72bd-11e7-9c5b-75353b85cebe.png)

**Comment by jcfr** [comment]
@fedorov I will assess and let you know what I find out.

For the record, CI also failed on July 25 on CircleCI and Appveyor.

**Comment by jcfr** [comment]
> but packages for all platforms are available for the latest commit

To be expected, unless new packages can be generated. The last one remain available.

**Comment by fedorov** [comment]
> For the record, CI also failed on July 25 on CircleCI and Appveyor.

Right, also in the process of release upload.

Appveyor:

```
[00:03:23] ci_addons : Traceback (most recent call last):
[00:03:23] At line:1 char:1
[00:03:23] + ci_addons publish_github_release qiicr/dcmqi `
[00:03:23] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:03:23]     + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
[00:03:23]     + FullyQualifiedErrorId : NativeCommandError
[00:03:23]  
[00:03:23]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 439, in <module>
[00:03:23]     main()
[00:03:23]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 432, in main
[00:03:23]     _upload_prerelease(args)
[00:03:23]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 342, in _upload_prerelease
[00:03:23]     target_commitish=sha
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 116, in with_check_for_credentials
[00:03:23]     return func(*args, **kwargs)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 479, in gh_release_edit
[00:03:23]     patch_release(repo_name, current_tag_name, **attributes)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 327, in patch_release
[00:03:23]     dry_run
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 301, in _update_release_sha
[00:03:23]     dry_run=dry_run)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 357, in patch_release
[00:03:23]     response.raise_for_status()
[00:03:23]   File "c:\python27-x64\lib\site-packages\requests\models.py", line 937, in raise_for_status
[00:03:23]     raise HTTPError(http_error_msg, response=self)
[00:03:23] requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:03:23] 
[00:03:23] Command executed with exception:   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 439, in <module>
[00:03:23]     main()
[00:03:23]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 432, in main
[00:03:23]     _upload_prerelease(args)
[00:03:23]   File "c:\python27-x64\lib\site-packages\anyci\publish_github_release.py", line 342, in _upload_prerelease
[00:03:23]     target_commitish=sha
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 116, in with_check_for_credentials
[00:03:23]     return func(*args, **kwargs)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 479, in gh_release_edit
[00:03:23]     patch_release(repo_name, current_tag_name, **attributes)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 327, in patch_release
[00:03:23]     dry_run
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 301, in _update_release_sha
[00:03:23]     dry_run=dry_run)
[00:03:23]   File "c:\python27-x64\lib\site-packages\github_release.py", line 357, in patch_release
[00:03:23]     response.raise_for_status()
[00:03:23]   File "c:\python27-x64\lib\site-packages\requests\models.py", line 937, in raise_for_status
[00:03:23]     raise HTTPError(http_error_msg, response=self)
[00:03:23] requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qiicr/dcmqi/releases/7049244
[00:03:23] 
```

CircleCI:

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/anyci/publish_github_release.py", line 439, in <module>
    main()
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/anyci/publish_github_release.py", line 432, in main
    _upload_prerelease(args)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/anyci/publish_github_release.py", line 342, in _upload_prerelease
    target_commitish=sha
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/github_release.py", line 479, in gh_release_edit
    patch_release(repo_name, current_tag_name, **attributes)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/github_release.py", line 327, in patch_release
    dry_run
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/github_release.py", line 301, in _update_release_sha
    dry_run=dry_run)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/github_release.py", line 357, in patch_release
    response.raise_for_status()
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qiicr/dcmqi/releases/7049244

ci_addons publish_github_release qiicr/dcmqi \
   --prerelease-packages "build/dcmqi-build/dcmqi-*-linux-*.tar.gz" \
   --prerelease-packages-clear-pattern "dcmqi-*-linux-*" \
   --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
 returned exit code 1

Action failed: ci_addons publish_github_release qiicr/dcmqi \
   --prerelease-packages "build/dcmqi-build/dcmqi-*-linux-*.tar.gz" \
   --prerelease-packages-clear-pattern "dcmqi-*-linux-*" \
   --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*"
```

**Comment by jcfr** [comment]
I am on it. It should be fixed shortly. 

Thanks again for your patience.

**Comment by jcfr** [comment]
This last issue should be addressed by https://github.com/QIICR/dcmqi/commit/95356d4d03868ae805630cb87c6aec08fa7319dc

I will make sure to follow up if issues remain.

**Comment by jcfr** [comment]
Closing. This issue is effectively addressed by #285

**Comment by fedorov** [comment]
Great, thank you @jcfr 👍 

One issue still remaining - isn't it a bug that it says "released this 14 days ago" for the latest release?

**Comment by jcfr** [comment]
> released this 14 days ago

Since the pre-release points to the latest commit, we can not do better here. May be submit an issue to Github ? 

Same behavior here: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/releases

Jc

**Comment by fedorov** [comment]
> pre-release points to the latest commit

Sorry, I am still not getting it - pre-release correctly points to https://github.com/QIICR/dcmqi/commit/95356d4d03868ae805630cb87c6aec08fa7319dc, which is the latest commit, and it is dated Jul 27.  What am I missing?

**Comment by jcfr** [comment]
>  What am I missing?

Nothing really.

As you mentioned, it points to the latest commit but show an earlier date. It is not specific to dcmqi. 
The name of the release is also up-to-date.

If you have resources to allocate, we could probably dig further and workaround the limitation. In the mean time, may be an issue could be reported to GitHub.

Related resources: https://developer.github.com/v3/repos/releases/#edit-a-release

**Comment by fedorov** [comment]
I see, so this is just a known issue. No, I don't consider it critical. I just wanted to see if this is not something that was missed. 

Thank you very much for the focused effort you put in to fix this in the last few days, I really appreciate your help and hard work! 👍
